// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

public partial class ConfigManager
{
    public bool IsReady { get; private set; }
    struct ConfigEntry { public string DataType; public string Value; }
    readonly Dictionary<ConfigType, ConfigEntry> _dict = new Dictionary<ConfigType, ConfigEntry>();

    public IEnumerator CoDownloadConfig()
    {
        IsReady = false;
        Debug.Log("[ConfigManager] Config 다운로드 시작");
        string url = GoogleSheetConfig.BuildJsonUrl("Config");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[ConfigManager] 다운로드 실패: " + req.error);
                IsReady = true; yield break;
            }
            _dict.Clear();
            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 4);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                try
                {
                    string dataType  = cells[1];
                    string configKey = cells[2];
                    string value     = cells[3];
                    if (!Enum.TryParse(configKey, true, out ConfigType key))
                    {
                        Debug.LogWarning("[ConfigManager] [Config] 알 수 없는 ConfigType: \"" + configKey + "\" (시트 행 " + sheetRow + ", 열 3)");
                        continue;
                    }
                    _dict[key] = new ConfigEntry { DataType = dataType, Value = value };
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[ConfigManager] [Config] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + "\n" +
                        "  값: [" + cells[1] + ", " + cells[2] + ", " + cells[3] + "]\n" +
                        "  원인: " + e.Message);
                }
            }
            Debug.Log("[ConfigManager] 로드 완료: " + _dict.Count + "개");
        }
        IsReady = true;
    }

    public int GetInt(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    public float GetFloat(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    public string GetString(ConfigType key) => GetRaw(key);
    public bool GetBool(ConfigType key)
    {
        string s = GetRaw(key);
        return s == "true" || s == "1" || s == "yes";
    }
    public long GetLong(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0L;
        if (s.Contains("."))
            return (long)double.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return long.Parse(s);
    }
    public object GetAuto(ConfigType key)
    {
        if (!_dict.TryGetValue(key, out ConfigEntry entry)) return null;
        return entry.DataType switch
        {
            "int"   => (object)GetInt(key),
            "float" => (object)GetFloat(key),
            "bool"  => (object)GetBool(key),
            "long"  => (object)GetLong(key),
            _       => (object)GetString(key),
        };
    }
    string GetRaw(ConfigType key) =>
        _dict.TryGetValue(key, out ConfigEntry e) ? e.Value : string.Empty;

}
