// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using Google.Protobuf.Protocol;

/// <summary>
/// Google Sheets JSON API를 런타임에 직접 호출하여 MetaData를 파싱합니다.
/// 빌드 후에도 시트 데이터 변경이 즉시 반영됩니다 (재빌드 불필요).
/// </summary>
public class SpecDataManager
{
    public bool IsReady { get; private set; }

    Dictionary<int, CurrencyMetaData> _currencyDict = new Dictionary<int, CurrencyMetaData>();
    List<CurrencyMetaData>            _currencyList = new List<CurrencyMetaData>();
    Dictionary<int, QuestDefinitionMetaData> _questDefinitionDict = new Dictionary<int, QuestDefinitionMetaData>();
    List<QuestDefinitionMetaData>            _questDefinitionList = new List<QuestDefinitionMetaData>();
    Dictionary<int, QuestObjectiveDefinitionMetaData> _questObjectiveDefinitionDict = new Dictionary<int, QuestObjectiveDefinitionMetaData>();
    List<QuestObjectiveDefinitionMetaData>            _questObjectiveDefinitionList = new List<QuestObjectiveDefinitionMetaData>();
    Dictionary<int, abcMetaData> _abcDict = new Dictionary<int, abcMetaData>();
    List<abcMetaData>            _abcList = new List<abcMetaData>();
    Dictionary<int, MonsterMetaData> _monsterDict = new Dictionary<int, MonsterMetaData>();
    List<MonsterMetaData>            _monsterList = new List<MonsterMetaData>();
    Dictionary<int, PlayerMetaData> _playerDict = new Dictionary<int, PlayerMetaData>();
    List<PlayerMetaData>            _playerList = new List<PlayerMetaData>();

    public IEnumerator CoDownloadDataSheet()
    {
        IsReady = false;
        Debug.Log("[SpecDataManager] 데이터 다운로드 시작");

        yield return CoFetch_Currency();
        yield return CoFetch_QuestDefinition();
        yield return CoFetch_QuestObjectiveDefinition();
        yield return CoFetch_abc();
        yield return CoFetch_Monster();
        yield return CoFetch_Player();

        IsReady = true;
        Debug.Log("[SpecDataManager] 모든 데이터 로드 완료");
    }

    IEnumerator CoFetch_Currency()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Currency");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Currency 다운로드 실패: " + req.error);
                yield break;
            }

            _currencyDict.Clear();
            _currencyList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    CurrencyMetaData data = new CurrencyMetaData
                    {
                        Id = ParseInt(cells[0]),
                        CurrencyType = ParseEnum<CurrencyType>(cells[1]),
                    };
                    _currencyDict[data.Id] = data;
                    _currencyList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Currency 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Currency 로드 완료: " + _currencyList.Count + "개");
        }
    }

    IEnumerator CoFetch_QuestDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestDefinition");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] QuestDefinition 다운로드 실패: " + req.error);
                yield break;
            }

            _questDefinitionDict.Clear();
            _questDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    QuestDefinitionMetaData data = new QuestDefinitionMetaData
                    {
                        Id = ParseInt(cells[0]),
                        QuestId = ParseInt(cells[1]),
                        QuestType = ParseEnum<QuestType>(cells[2]),
                        Title = cells[3],
                        ReqLevel = ParseInt(cells[4]),
                        PrereqQuestId = ParseInt(cells[5]),
                        RewardId = ParseInt(cells[6]),
                        RewardAmount = ParseInt(cells[7]),
                        Description = cells[8],
                    };
                    _questDefinitionDict[data.Id] = data;
                    _questDefinitionList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] QuestDefinition 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] QuestDefinition 로드 완료: " + _questDefinitionList.Count + "개");
        }
    }

    IEnumerator CoFetch_QuestObjectiveDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestObjectiveDefinition");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] QuestObjectiveDefinition 다운로드 실패: " + req.error);
                yield break;
            }

            _questObjectiveDefinitionDict.Clear();
            _questObjectiveDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    QuestObjectiveDefinitionMetaData data = new QuestObjectiveDefinitionMetaData
                    {
                        Id = ParseInt(cells[0]),
                        MainQuestId = ParseInt(cells[1]),
                        SubQuestId = cells[2],
                        QuestObjectiveType = ParseEnum<QuestObjectiveType>(cells[3]),
                        TargetId = ParseInt(cells[4]),
                        RequiredCount = ParseInt(cells[5]),
                        RewardId = ParseInt(cells[6]),
                        RewardAmount = ParseInt(cells[7]),
                        Description = cells[8],
                    };
                    _questObjectiveDefinitionDict[data.Id] = data;
                    _questObjectiveDefinitionList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] QuestObjectiveDefinition 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] QuestObjectiveDefinition 로드 완료: " + _questObjectiveDefinitionList.Count + "개");
        }
    }

    IEnumerator CoFetch_abc()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("abc");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] abc 다운로드 실패: " + req.error);
                yield break;
            }

            _abcDict.Clear();
            _abcList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 1);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    abcMetaData data = new abcMetaData
                    {
                        Id = ParseInt(cells[0]),
                    };
                    _abcDict[data.Id] = data;
                    _abcList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] abc 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] abc 로드 완료: " + _abcList.Count + "개");
        }
    }

    IEnumerator CoFetch_Monster()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Monster");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Monster 다운로드 실패: " + req.error);
                yield break;
            }

            _monsterDict.Clear();
            _monsterList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 13);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    MonsterMetaData data = new MonsterMetaData
                    {
                        Id = ParseInt(cells[0]),
                        MonsterType = ParseEnum<MonsterType>(cells[1]),
                        MaxHp = ParseInt(cells[2]),
                        CommonAttackDamage = ParseFloat(cells[3]),
                        CommonAttackCoolTime = ParseFloat(cells[4]),
                        AttackRange = ParseFloat(cells[5]),
                        Defense = ParseFloat(cells[6]),
                        MoveSpeed = ParseFloat(cells[7]),
                        Level = ParseInt(cells[8]),
                        Exp = ParseInt(cells[9]),
                        Gold = ParseInt(cells[10]),
                        SearchRange = ParseFloat(cells[11]),
                        RespawnTime = ParseFloat(cells[12]),
                    };
                    _monsterDict[data.Id] = data;
                    _monsterList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Monster 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Monster 로드 완료: " + _monsterList.Count + "개");
        }
    }

    IEnumerator CoFetch_Player()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Player");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Player 다운로드 실패: " + req.error);
                yield break;
            }

            _playerDict.Clear();
            _playerList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 1);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    PlayerMetaData data = new PlayerMetaData
                    {
                        Id = ParseInt(cells[0]),
                    };
                    _playerDict[data.Id] = data;
                    _playerList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Player 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Player 로드 완료: " + _playerList.Count + "개");
        }
    }

    public CurrencyMetaData GetCurrency(int id)
    {
        _currencyDict.TryGetValue(id, out CurrencyMetaData result);
        return result;
    }

    public CurrencyMetaData GetCurrency(CurrencyType key)
    {
        return GetCurrency((int)key);
    }

    public List<CurrencyMetaData> GetAllCurrency()
    {
        return _currencyList;
    }

    public QuestDefinitionMetaData GetQuestDefinition(int id)
    {
        _questDefinitionDict.TryGetValue(id, out QuestDefinitionMetaData result);
        return result;
    }

    public QuestDefinitionMetaData GetQuestDefinition(QuestType key)
    {
        return GetQuestDefinition((int)key);
    }

    public List<QuestDefinitionMetaData> GetAllQuestDefinition()
    {
        return _questDefinitionList;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(int id)
    {
        _questObjectiveDefinitionDict.TryGetValue(id, out QuestObjectiveDefinitionMetaData result);
        return result;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(QuestObjectiveType key)
    {
        return GetQuestObjectiveDefinition((int)key);
    }

    public List<QuestObjectiveDefinitionMetaData> GetAllQuestObjectiveDefinition()
    {
        return _questObjectiveDefinitionList;
    }

    public abcMetaData Getabc(int id)
    {
        _abcDict.TryGetValue(id, out abcMetaData result);
        return result;
    }

    public List<abcMetaData> GetAllabc()
    {
        return _abcList;
    }

    public MonsterMetaData GetMonster(int id)
    {
        _monsterDict.TryGetValue(id, out MonsterMetaData result);
        return result;
    }

    public MonsterMetaData GetMonster(MonsterType key)
    {
        return GetMonster((int)key);
    }

    public List<MonsterMetaData> GetAllMonster()
    {
        return _monsterList;
    }

    public PlayerMetaData GetPlayer(int id)
    {
        _playerDict.TryGetValue(id, out PlayerMetaData result);
        return result;
    }

    public List<PlayerMetaData> GetAllPlayer()
    {
        return _playerList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default;
        return (T)Enum.Parse(typeof(T), s, true);
    }
}
