// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using Google.Protobuf.Protocol;

/// <summary>
/// Google Sheets JSON API를 런타임에 직접 호출하여 MetaData를 파싱합니다.
/// 빌드 후에도 시트 데이터 변경이 즉시 반영됩니다 (재빌드 불필요).
/// </summary>
public partial class SpecDataManager
{
    public bool IsReady { get; private set; }

    Dictionary<int, CurrencyMetaData> _currencyDict = new Dictionary<int, CurrencyMetaData>();
    List<CurrencyMetaData>            _currencyList = new List<CurrencyMetaData>();
    Dictionary<int, QuestDefinitionMetaData> _questDefinitionDict = new Dictionary<int, QuestDefinitionMetaData>();
    List<QuestDefinitionMetaData>            _questDefinitionList = new List<QuestDefinitionMetaData>();
    Dictionary<int, QuestObjectiveDefinitionMetaData> _questObjectiveDefinitionDict = new Dictionary<int, QuestObjectiveDefinitionMetaData>();
    List<QuestObjectiveDefinitionMetaData>            _questObjectiveDefinitionList = new List<QuestObjectiveDefinitionMetaData>();
    Dictionary<int, MonsterMetaData> _monsterDict = new Dictionary<int, MonsterMetaData>();
    List<MonsterMetaData>            _monsterList = new List<MonsterMetaData>();
    Dictionary<int, PlayerMetaData> _playerDict = new Dictionary<int, PlayerMetaData>();
    List<PlayerMetaData>            _playerList = new List<PlayerMetaData>();

    public IEnumerator CoDownloadDataSheet()
    {
        IsReady = false;
        Debug.Log("[SpecDataManager] 데이터 다운로드 시작");

        yield return CoFetch_Currency();
        yield return CoFetch_QuestDefinition();
        yield return CoFetch_QuestObjectiveDefinition();
        yield return CoFetch_Monster();
        yield return CoFetch_Player();

        IsReady = true;
        Debug.Log("[SpecDataManager] 모든 데이터 로드 완료");
    }

    IEnumerator CoFetch_Currency()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Currency");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Currency 다운로드 실패: " + req.error);
                yield break;
            }

            _currencyDict.Clear();
            _currencyList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                CurrencyMetaData data = new CurrencyMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Currency] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CurrencyType (enum)
                try { data.CurrencyType = ParseEnum<CurrencyType>(cells[1]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Currency] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (CurrencyType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _currencyDict[data.Id] = data;
                    _currencyList.Add(data);
                }
                else
                {
                    Debug.LogWarning("[SpecDataManager] [Currency] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }

            Debug.Log("[SpecDataManager] Currency 로드 완료: " + _currencyList.Count + "개");
        }
    }

    IEnumerator CoFetch_QuestDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestDefinition");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] QuestDefinition 다운로드 실패: " + req.error);
                yield break;
            }

            _questDefinitionDict.Clear();
            _questDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                QuestDefinitionMetaData data = new QuestDefinitionMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MainQuestId (int)
                try { data.MainQuestId = ParseInt(cells[1]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MainQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // QuestType (enum)
                try { data.QuestType = ParseEnum<QuestType>(cells[2]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (QuestType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Title (string)
                try { data.Title = cells[3]; }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (Title)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // ReqLevel (int)
                try { data.ReqLevel = ParseInt(cells[4]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (ReqLevel)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // PrereqQuestId (int)
                try { data.PrereqQuestId = ParseInt(cells[5]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (PrereqQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardId (int)
                try { data.RewardId = ParseInt(cells[6]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (RewardId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardAmount (int)
                try { data.RewardAmount = ParseInt(cells[7]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (RewardAmount)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Description (string)
                try { data.Description = cells[8]; }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 9 (Description)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[8] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _questDefinitionDict[data.Id] = data;
                    _questDefinitionList.Add(data);
                }
                else
                {
                    Debug.LogWarning("[SpecDataManager] [QuestDefinition] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }

            Debug.Log("[SpecDataManager] QuestDefinition 로드 완료: " + _questDefinitionList.Count + "개");
        }
    }

    IEnumerator CoFetch_QuestObjectiveDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestObjectiveDefinition");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] QuestObjectiveDefinition 다운로드 실패: " + req.error);
                yield break;
            }

            _questObjectiveDefinitionDict.Clear();
            _questObjectiveDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                QuestObjectiveDefinitionMetaData data = new QuestObjectiveDefinitionMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MainQuestId (int)
                try { data.MainQuestId = ParseInt(cells[1]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MainQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // SubQuestId (int)
                try { data.SubQuestId = ParseInt(cells[2]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (SubQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // QuestObjectiveType (enum)
                try { data.QuestObjectiveType = ParseEnum<QuestObjectiveType>(cells[3]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (QuestObjectiveType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // TargetId (int)
                try { data.TargetId = ParseInt(cells[4]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (TargetId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RequiredCount (int)
                try { data.RequiredCount = ParseInt(cells[5]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (RequiredCount)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardId (int)
                try { data.RewardId = ParseInt(cells[6]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (RewardId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardAmount (int)
                try { data.RewardAmount = ParseInt(cells[7]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (RewardAmount)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Description (string)
                try { data.Description = cells[8]; }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 9 (Description)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[8] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _questObjectiveDefinitionDict[data.Id] = data;
                    _questObjectiveDefinitionList.Add(data);
                }
                else
                {
                    Debug.LogWarning("[SpecDataManager] [QuestObjectiveDefinition] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }

            Debug.Log("[SpecDataManager] QuestObjectiveDefinition 로드 완료: " + _questObjectiveDefinitionList.Count + "개");
        }
    }

    IEnumerator CoFetch_Monster()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Monster");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Monster 다운로드 실패: " + req.error);
                yield break;
            }

            _monsterDict.Clear();
            _monsterList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 13);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                MonsterMetaData data = new MonsterMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MonsterType (enum)
                try { data.MonsterType = ParseEnum<MonsterType>(cells[1]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MonsterType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MaxHp (int)
                try { data.MaxHp = ParseInt(cells[2]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (MaxHp)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CommonAttackDamage (float)
                try { data.CommonAttackDamage = ParseFloat(cells[3]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (CommonAttackDamage)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CommonAttackCoolTime (float)
                try { data.CommonAttackCoolTime = ParseFloat(cells[4]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (CommonAttackCoolTime)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // AttackRange (float)
                try { data.AttackRange = ParseFloat(cells[5]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (AttackRange)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Defense (float)
                try { data.Defense = ParseFloat(cells[6]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (Defense)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MoveSpeed (float)
                try { data.MoveSpeed = ParseFloat(cells[7]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (MoveSpeed)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Level (int)
                try { data.Level = ParseInt(cells[8]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 9 (Level)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[8] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Exp (int)
                try { data.Exp = ParseInt(cells[9]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 10 (Exp)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[9] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Gold (int)
                try { data.Gold = ParseInt(cells[10]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 11 (Gold)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[10] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // SearchRange (float)
                try { data.SearchRange = ParseFloat(cells[11]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 12 (SearchRange)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[11] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RespawnTime (float)
                try { data.RespawnTime = ParseFloat(cells[12]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 13 (RespawnTime)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[12] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _monsterDict[data.Id] = data;
                    _monsterList.Add(data);
                }
                else
                {
                    Debug.LogWarning("[SpecDataManager] [Monster] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }

            Debug.Log("[SpecDataManager] Monster 로드 완료: " + _monsterList.Count + "개");
        }
    }

    IEnumerator CoFetch_Player()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Player");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Player 다운로드 실패: " + req.error);
                yield break;
            }

            _playerDict.Clear();
            _playerList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 1);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                PlayerMetaData data = new PlayerMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] [Player] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _playerDict[data.Id] = data;
                    _playerList.Add(data);
                }
                else
                {
                    Debug.LogWarning("[SpecDataManager] [Player] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }

            Debug.Log("[SpecDataManager] Player 로드 완료: " + _playerList.Count + "개");
        }
    }

    public CurrencyMetaData GetCurrency(int id)
    {
        _currencyDict.TryGetValue(id, out CurrencyMetaData result);
        return result;
    }

    public CurrencyMetaData GetCurrency(CurrencyType key)
    {
        return GetCurrency((int)key);
    }

    public List<CurrencyMetaData> GetAllCurrency()
    {
        return _currencyList;
    }

    public QuestDefinitionMetaData GetQuestDefinition(int id)
    {
        _questDefinitionDict.TryGetValue(id, out QuestDefinitionMetaData result);
        return result;
    }

    public QuestDefinitionMetaData GetQuestDefinition(QuestType key)
    {
        return GetQuestDefinition((int)key);
    }

    public List<QuestDefinitionMetaData> GetAllQuestDefinition()
    {
        return _questDefinitionList;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(int id)
    {
        _questObjectiveDefinitionDict.TryGetValue(id, out QuestObjectiveDefinitionMetaData result);
        return result;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(QuestObjectiveType key)
    {
        return GetQuestObjectiveDefinition((int)key);
    }

    public List<QuestObjectiveDefinitionMetaData> GetAllQuestObjectiveDefinition()
    {
        return _questObjectiveDefinitionList;
    }

    public MonsterMetaData GetMonster(int id)
    {
        _monsterDict.TryGetValue(id, out MonsterMetaData result);
        return result;
    }

    public MonsterMetaData GetMonster(MonsterType key)
    {
        return GetMonster((int)key);
    }

    public List<MonsterMetaData> GetAllMonster()
    {
        return _monsterList;
    }

    public PlayerMetaData GetPlayer(int id)
    {
        _playerDict.TryGetValue(id, out PlayerMetaData result);
        return result;
    }

    public List<PlayerMetaData> GetAllPlayer()
    {
        return _playerList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default;
        return (T)Enum.Parse(typeof(T), s, true);
    }
}
