// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

/// <summary>
/// Google Sheets JSON API를 런타임에 직접 호출하여 MetaData를 파싱합니다.
/// 빌드 후에도 시트 데이터 변경이 즉시 반영됩니다 (재빌드 불필요).
/// </summary>
public class SpecDataManager
{
    public bool IsReady { get; private set; }

    Dictionary<int, PlayerMetaData> _playerDict = new Dictionary<int, PlayerMetaData>();
    List<PlayerMetaData>            _playerList = new List<PlayerMetaData>();

    public IEnumerator CoDownloadDataSheet()
    {
        IsReady = false;
        Debug.Log("[SpecDataManager] 데이터 다운로드 시작");

        yield return CoFetch_Player();

        IsReady = true;
        Debug.Log("[SpecDataManager] 모든 데이터 로드 완료");
    }

    IEnumerator CoFetch_Player()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Player");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Player 다운로드 실패: " + req.error);
                yield break;
            }

            _playerDict.Clear();
            _playerList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 1);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    PlayerMetaData data = new PlayerMetaData
                    {
                        Id = ParseInt(cells[0]),
                    };
                    _playerDict[data.Id] = data;
                    _playerList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Player 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Player 로드 완료: " + _playerList.Count + "개");
        }
    }

    public PlayerMetaData GetPlayer(int id)
    {
        PlayerMetaData result;
        _playerDict.TryGetValue(id, out result);
        return result;
    }


    public List<PlayerMetaData> GetAllPlayer()
    {
        return _playerList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default(T);
        return (T)Enum.Parse(typeof(T), s, true);
    }
}
