// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================

namespace Server.Data
{
    public enum ItemType
    {
        None = 0,
        Equipment = 100000,
        Consumable = 200000,
        Misc = 300000,
    }
    
    public enum ItemGrade
    {
        None = 0,
        Normal = 100000,
        Rare = 200000,
        Epic = 300000,
    }
    
    public enum EquipmentType
    {
        None = 0,
        BasicSword = 100000,
    }
    
    public enum EquipSlotType
    {
        None = 0,
        MainWeapon = 100000,
    }
    
    public enum ConsumableType
    {
        None = 0,
        BasicRecoveryHpPotion = 200000,
    }
    
    public enum MiscType
    {
        None = 0,
        BearLeather = 300000,
    }
    
    public enum ConfigType
    {
        None = 0,
        RequiredIdleTime = 1,
        DefaultCreationMainQuestId = 2,
        DefaultCreationSubQuestId = 3,
        DefaultInventorySize = 4,
        EquipmentStartId = 5,
        ConsumableStartId = 6,
        MiscStartId = 7,
        DefaultEquimentInventorySize = 8,
        DefaultConsumableInventorySize = 9,
        DefaultMiscInventorySize = 10,
    }
    
    
}
