// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================

namespace Server.Data
{
    public enum ItemGrade
    {
        None = 0,
        Normal,
        Rare,
        Epic,
    }
    
    public enum EquipmentType
    {
        None = 0,
        BasicSword = 100000,
        BasicShield = 100001,
        BasicHelmet = 100002,
        BasicChest = 100003,
        BasicPants = 100004,
        BasicBoots = 100005,
        FlyBoots = 100006,
    }
    
    public enum ConsumableType
    {
        None = 0,
        BasicRecoveryHpPotion = 200000,
    }
    
    public enum MiscType
    {
        None = 0,
        BearLeather = 300000,
    }
    
    public enum ConfigType
    {
        None = 0,
        RequiredIdleTime = 1,
        DefaultCreationMainQuestId = 2,
        DefaultCreationSubQuestId = 3,
        DefaultInventorySize = 4,
        EquipmentStartId = 5,
        ConsumableStartId = 6,
        MiscStartId = 7,
        DefaultEquimentInventorySize = 8,
        DefaultConsumableInventorySize = 9,
        DefaultMiscInventorySize = 10,
        DropItemPickupRadius = 11,
        AutoSaveDBIntervalMs = 12,
        DefaultStartMapId = 13,
    }
    
    public enum SkillCategoryType
    {
        None = 0,
        Attack,
    }
    
    public enum SkillAttackKind
    {
        None = 0,
        Ranged = 1,
        Melee = 2,
    }
    
    public enum BuffValueType
    {
        None = 0,
        Percent = 1,
        Flat = 2,
    }
    
    
}
