// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================

namespace Server.Data
{
    public enum ConfigType
    {
        None = 0,
        RequiredIdleTime,
    }
    
    
}
