// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Google.Protobuf.Protocol;

namespace Server.Data
{
public partial class SpecDataManager
{
    #region Singleton
    public static SpecDataManager Instance { get; } = new SpecDataManager();
    SpecDataManager() { }
    #endregion

    static readonly HttpClient Http = new HttpClient();
    public bool IsReady { get; private set; }

    Dictionary<int, CurrencyMetaData> _currencyDict = new Dictionary<int, CurrencyMetaData>();
    List<CurrencyMetaData>            _currencyList = new List<CurrencyMetaData>();
    Dictionary<int, QuestDefinitionMetaData> _questDefinitionDict = new Dictionary<int, QuestDefinitionMetaData>();
    List<QuestDefinitionMetaData>            _questDefinitionList = new List<QuestDefinitionMetaData>();
    Dictionary<int, QuestObjectiveDefinitionMetaData> _questObjectiveDefinitionDict = new Dictionary<int, QuestObjectiveDefinitionMetaData>();
    List<QuestObjectiveDefinitionMetaData>            _questObjectiveDefinitionList = new List<QuestObjectiveDefinitionMetaData>();
    Dictionary<int, MonsterMetaData> _monsterDict = new Dictionary<int, MonsterMetaData>();
    List<MonsterMetaData>            _monsterList = new List<MonsterMetaData>();
    Dictionary<int, PlayerMetaData> _playerDict = new Dictionary<int, PlayerMetaData>();
    List<PlayerMetaData>            _playerList = new List<PlayerMetaData>();

    public async Task DownloadDataSheet()
    {
        IsReady = false;
        Console.WriteLine("[SpecDataManager] 데이터 다운로드 시작");

        await Fetch_Currency();
        await Fetch_QuestDefinition();
        await Fetch_QuestObjectiveDefinition();
        await Fetch_Monster();
        await Fetch_Player();

        IsReady = true;
        Console.WriteLine("[SpecDataManager] 모든 데이터 로드 완료");
    }

    async Task Fetch_Currency()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Currency");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _currencyDict.Clear();
            _currencyList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    CurrencyMetaData data = new CurrencyMetaData
                    {
                        Id = ParseInt(cells[0]),
                        CurrencyType = ParseEnum<CurrencyType>(cells[1]),
                    };
                    _currencyDict[data.Id] = data;
                    _currencyList.Add(data);
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] Currency 파싱 오류 row" + i + ": " + e.Message);
                }
            }
            Console.WriteLine("[SpecDataManager] Currency 로드 완료: " + _currencyList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Currency 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_QuestDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestDefinition");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _questDefinitionDict.Clear();
            _questDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    QuestDefinitionMetaData data = new QuestDefinitionMetaData
                    {
                        Id = ParseInt(cells[0]),
                        QuestId = ParseInt(cells[1]),
                        QuestType = ParseEnum<QuestType>(cells[2]),
                        Title = cells[3],
                        ReqLevel = ParseInt(cells[4]),
                        PrereqQuestId = ParseInt(cells[5]),
                        RewardId = ParseInt(cells[6]),
                        RewardAmount = ParseInt(cells[7]),
                        Description = cells[8],
                    };
                    _questDefinitionDict[data.Id] = data;
                    _questDefinitionList.Add(data);
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] QuestDefinition 파싱 오류 row" + i + ": " + e.Message);
                }
            }
            Console.WriteLine("[SpecDataManager] QuestDefinition 로드 완료: " + _questDefinitionList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] QuestDefinition 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_QuestObjectiveDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestObjectiveDefinition");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _questObjectiveDefinitionDict.Clear();
            _questObjectiveDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    QuestObjectiveDefinitionMetaData data = new QuestObjectiveDefinitionMetaData
                    {
                        Id = ParseInt(cells[0]),
                        MainQuestId = ParseInt(cells[1]),
                        SubQuestId = ParseInt(cells[2]),
                        QuestObjectiveType = ParseEnum<QuestObjectiveType>(cells[3]),
                        TargetId = ParseInt(cells[4]),
                        RequiredCount = ParseInt(cells[5]),
                        RewardId = ParseInt(cells[6]),
                        RewardAmount = ParseInt(cells[7]),
                        Description = cells[8],
                    };
                    _questObjectiveDefinitionDict[data.Id] = data;
                    _questObjectiveDefinitionList.Add(data);
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] QuestObjectiveDefinition 파싱 오류 row" + i + ": " + e.Message);
                }
            }
            Console.WriteLine("[SpecDataManager] QuestObjectiveDefinition 로드 완료: " + _questObjectiveDefinitionList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] QuestObjectiveDefinition 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Monster()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Monster");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _monsterDict.Clear();
            _monsterList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 13);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    MonsterMetaData data = new MonsterMetaData
                    {
                        Id = ParseInt(cells[0]),
                        MonsterType = ParseEnum<MonsterType>(cells[1]),
                        MaxHp = ParseInt(cells[2]),
                        CommonAttackDamage = ParseFloat(cells[3]),
                        CommonAttackCoolTime = ParseFloat(cells[4]),
                        AttackRange = ParseFloat(cells[5]),
                        Defense = ParseFloat(cells[6]),
                        MoveSpeed = ParseFloat(cells[7]),
                        Level = ParseInt(cells[8]),
                        Exp = ParseInt(cells[9]),
                        Gold = ParseInt(cells[10]),
                        SearchRange = ParseFloat(cells[11]),
                        RespawnTime = ParseFloat(cells[12]),
                    };
                    _monsterDict[data.Id] = data;
                    _monsterList.Add(data);
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] Monster 파싱 오류 row" + i + ": " + e.Message);
                }
            }
            Console.WriteLine("[SpecDataManager] Monster 로드 완료: " + _monsterList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Monster 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Player()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Player");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _playerDict.Clear();
            _playerList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 1);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    PlayerMetaData data = new PlayerMetaData
                    {
                        Id = ParseInt(cells[0]),
                    };
                    _playerDict[data.Id] = data;
                    _playerList.Add(data);
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] Player 파싱 오류 row" + i + ": " + e.Message);
                }
            }
            Console.WriteLine("[SpecDataManager] Player 로드 완료: " + _playerList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Player 다운로드 실패: " + ex.Message);
        }
    }

    public CurrencyMetaData GetCurrency(int id)
    {
        _currencyDict.TryGetValue(id, out CurrencyMetaData result);
        return result;
    }

    public CurrencyMetaData GetCurrency(CurrencyType key)
    {
        return GetCurrency((int)key);
    }

    public List<CurrencyMetaData> GetAllCurrency()
    {
        return _currencyList;
    }

    public QuestDefinitionMetaData GetQuestDefinition(int id)
    {
        _questDefinitionDict.TryGetValue(id, out QuestDefinitionMetaData result);
        return result;
    }

    public QuestDefinitionMetaData GetQuestDefinition(QuestType key)
    {
        return GetQuestDefinition((int)key);
    }

    public List<QuestDefinitionMetaData> GetAllQuestDefinition()
    {
        return _questDefinitionList;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(int id)
    {
        _questObjectiveDefinitionDict.TryGetValue(id, out QuestObjectiveDefinitionMetaData result);
        return result;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(QuestObjectiveType key)
    {
        return GetQuestObjectiveDefinition((int)key);
    }

    public List<QuestObjectiveDefinitionMetaData> GetAllQuestObjectiveDefinition()
    {
        return _questObjectiveDefinitionList;
    }

    public MonsterMetaData GetMonster(int id)
    {
        _monsterDict.TryGetValue(id, out MonsterMetaData result);
        return result;
    }

    public MonsterMetaData GetMonster(MonsterType key)
    {
        return GetMonster((int)key);
    }

    public List<MonsterMetaData> GetAllMonster()
    {
        return _monsterList;
    }

    public PlayerMetaData GetPlayer(int id)
    {
        _playerDict.TryGetValue(id, out PlayerMetaData result);
        return result;
    }

    public List<PlayerMetaData> GetAllPlayer()
    {
        return _playerList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default;
        return (T)Enum.Parse(typeof(T), s, true);
    }
}
}
