// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Google.Protobuf.Protocol;

namespace Server.Data
{
public partial class SpecDataManager
{
    #region Singleton
    public static SpecDataManager Instance { get; } = new SpecDataManager();
    SpecDataManager() { }
    #endregion

    static readonly HttpClient Http = new HttpClient();
    public bool IsReady { get; private set; }

    Dictionary<int, CurrencyMetaData> _currencyDict = new Dictionary<int, CurrencyMetaData>();
    List<CurrencyMetaData>            _currencyList = new List<CurrencyMetaData>();
    Dictionary<int, ItemMetaData> _itemDict = new Dictionary<int, ItemMetaData>();
    List<ItemMetaData>            _itemList = new List<ItemMetaData>();
    Dictionary<int, EquipmentMetaData> _equipmentDict = new Dictionary<int, EquipmentMetaData>();
    List<EquipmentMetaData>            _equipmentList = new List<EquipmentMetaData>();
    Dictionary<int, ConsumableMetaData> _consumableDict = new Dictionary<int, ConsumableMetaData>();
    List<ConsumableMetaData>            _consumableList = new List<ConsumableMetaData>();
    Dictionary<int, MiscMetaData> _miscDict = new Dictionary<int, MiscMetaData>();
    List<MiscMetaData>            _miscList = new List<MiscMetaData>();
    Dictionary<int, QuestDefinitionMetaData> _questDefinitionDict = new Dictionary<int, QuestDefinitionMetaData>();
    List<QuestDefinitionMetaData>            _questDefinitionList = new List<QuestDefinitionMetaData>();
    Dictionary<int, QuestObjectiveDefinitionMetaData> _questObjectiveDefinitionDict = new Dictionary<int, QuestObjectiveDefinitionMetaData>();
    List<QuestObjectiveDefinitionMetaData>            _questObjectiveDefinitionList = new List<QuestObjectiveDefinitionMetaData>();
    Dictionary<int, MonsterMetaData> _monsterDict = new Dictionary<int, MonsterMetaData>();
    List<MonsterMetaData>            _monsterList = new List<MonsterMetaData>();
    Dictionary<int, PlayerMetaData> _playerDict = new Dictionary<int, PlayerMetaData>();
    List<PlayerMetaData>            _playerList = new List<PlayerMetaData>();

    public async Task DownloadDataSheet()
    {
        IsReady = false;
        Console.WriteLine("[SpecDataManager] 데이터 다운로드 시작");

        await Fetch_Currency();
        await Fetch_Item();
        await Fetch_Equipment();
        await Fetch_Consumable();
        await Fetch_Misc();
        await Fetch_QuestDefinition();
        await Fetch_QuestObjectiveDefinition();
        await Fetch_Monster();
        await Fetch_Player();

        IsReady = true;
        Console.WriteLine("[SpecDataManager] 모든 데이터 로드 완료");
    }

    async Task Fetch_Currency()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Currency");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _currencyDict.Clear();
            _currencyList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                CurrencyMetaData data = new CurrencyMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Currency] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CurrencyType (enum)
                try { data.CurrencyType = ParseEnum<CurrencyType>(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Currency] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (CurrencyType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _currencyDict[data.Id] = data;
                    _currencyList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Currency] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Currency 로드 완료: " + _currencyList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Currency 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Item()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Item");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _itemDict.Clear();
            _itemList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 8);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                ItemMetaData data = new ItemMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // ItemType (enum)
                try { data.ItemType = ParseEnum<ItemType>(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (ItemType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // ItemGrade (enum)
                try { data.ItemGrade = ParseEnum<ItemGrade>(cells[2]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (ItemGrade)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // ItemName (string)
                try { data.ItemName = cells[3]; }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (ItemName)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MaxStack (int)
                try { data.MaxStack = ParseInt(cells[4]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (MaxStack)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CanSell (bool)
                try { data.CanSell = (cells[5] == "true" || cells[5] == "1" || cells[5] == "yes"); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (CanSell)\n" +
                        "  타입: bool\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // SellPrice (int)
                try { data.SellPrice = ParseInt(cells[6]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (SellPrice)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Description (string)
                try { data.Description = cells[7]; }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (Description)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _itemDict[data.Id] = data;
                    _itemList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Item] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Item 로드 완료: " + _itemList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Item 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Equipment()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Equipment");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _equipmentDict.Clear();
            _equipmentList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 6);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                EquipmentMetaData data = new EquipmentMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // EquipmentType (enum)
                try { data.EquipmentType = ParseEnum<EquipmentType>(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (EquipmentType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // EquipSlotType (enum)
                try { data.EquipSlotType = ParseEnum<EquipSlotType>(cells[2]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (EquipSlotType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Attack (float)
                try { data.Attack = ParseFloat(cells[3]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (Attack)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Defense (float)
                try { data.Defense = ParseFloat(cells[4]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (Defense)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RequiredLevel (int)
                try { data.RequiredLevel = ParseInt(cells[5]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (RequiredLevel)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _equipmentDict[data.Id] = data;
                    _equipmentList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Equipment] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Equipment 로드 완료: " + _equipmentList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Equipment 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Consumable()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Consumable");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _consumableDict.Clear();
            _consumableList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 5);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                ConsumableMetaData data = new ConsumableMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Consumable] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // ConsumableType (enum)
                try { data.ConsumableType = ParseEnum<ConsumableType>(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Consumable] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (ConsumableType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // EffectValue (float)
                try { data.EffectValue = ParseFloat(cells[2]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Consumable] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (EffectValue)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Duration (float)
                try { data.Duration = ParseFloat(cells[3]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Consumable] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (Duration)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CoolTime (float)
                try { data.CoolTime = ParseFloat(cells[4]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Consumable] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (CoolTime)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _consumableDict[data.Id] = data;
                    _consumableList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Consumable] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Consumable 로드 완료: " + _consumableList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Consumable 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Misc()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Misc");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _miscDict.Clear();
            _miscList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                MiscMetaData data = new MiscMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Misc] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MiscType (enum)
                try { data.MiscType = ParseEnum<MiscType>(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Misc] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MiscType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _miscDict[data.Id] = data;
                    _miscList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Misc] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Misc 로드 완료: " + _miscList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Misc 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_QuestDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestDefinition");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _questDefinitionDict.Clear();
            _questDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 10);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                QuestDefinitionMetaData data = new QuestDefinitionMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MainQuestId (int)
                try { data.MainQuestId = ParseInt(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MainQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // QuestType (enum)
                try { data.QuestType = ParseEnum<QuestType>(cells[2]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (QuestType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Title (string)
                try { data.Title = cells[3]; }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (Title)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // ReqLevel (int)
                try { data.ReqLevel = ParseInt(cells[4]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (ReqLevel)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // PrereqQuestId (int)
                try { data.PrereqQuestId = ParseInt(cells[5]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (PrereqQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardIdList (list<int>)
                try { data.RewardIdList = ParseList(cells[6], s => ParseInt(s)); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (RewardIdList)\n" +
                        "  타입: list<int>\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardAmountList (list<int>)
                try { data.RewardAmountList = ParseList(cells[7], s => ParseInt(s)); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (RewardAmountList)\n" +
                        "  타입: list<int>\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // NextQuestIdList (list<int>)
                try { data.NextQuestIdList = ParseList(cells[8], s => ParseInt(s)); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 9 (NextQuestIdList)\n" +
                        "  타입: list<int>\n" +
                        "  값: \"" + cells[8] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Description (string)
                try { data.Description = cells[9]; }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 10 (Description)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[9] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _questDefinitionDict[data.Id] = data;
                    _questDefinitionList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestDefinition] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] QuestDefinition 로드 완료: " + _questDefinitionList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] QuestDefinition 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_QuestObjectiveDefinition()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("QuestObjectiveDefinition");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _questObjectiveDefinitionDict.Clear();
            _questObjectiveDefinitionList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 9);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                QuestObjectiveDefinitionMetaData data = new QuestObjectiveDefinitionMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MainQuestId (int)
                try { data.MainQuestId = ParseInt(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MainQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // SubQuestId (int)
                try { data.SubQuestId = ParseInt(cells[2]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (SubQuestId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // QuestObjectiveType (enum)
                try { data.QuestObjectiveType = ParseEnum<QuestObjectiveType>(cells[3]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (QuestObjectiveType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // TargetId (int)
                try { data.TargetId = ParseInt(cells[4]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (TargetId)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RequiredCount (int)
                try { data.RequiredCount = ParseInt(cells[5]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (RequiredCount)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardIdList (list<int>)
                try { data.RewardIdList = ParseList(cells[6], s => ParseInt(s)); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (RewardIdList)\n" +
                        "  타입: list<int>\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RewardAmountList (list<int>)
                try { data.RewardAmountList = ParseList(cells[7], s => ParseInt(s)); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (RewardAmountList)\n" +
                        "  타입: list<int>\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Description (string)
                try { data.Description = cells[8]; }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 9 (Description)\n" +
                        "  타입: string\n" +
                        "  값: \"" + cells[8] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _questObjectiveDefinitionDict[data.Id] = data;
                    _questObjectiveDefinitionList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [QuestObjectiveDefinition] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] QuestObjectiveDefinition 로드 완료: " + _questObjectiveDefinitionList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] QuestObjectiveDefinition 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Monster()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Monster");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _monsterDict.Clear();
            _monsterList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 13);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                MonsterMetaData data = new MonsterMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MonsterType (enum)
                try { data.MonsterType = ParseEnum<MonsterType>(cells[1]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 2 (MonsterType)\n" +
                        "  타입: enum\n" +
                        "  값: \"" + cells[1] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MaxHp (int)
                try { data.MaxHp = ParseInt(cells[2]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 3 (MaxHp)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[2] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CommonAttackDamage (float)
                try { data.CommonAttackDamage = ParseFloat(cells[3]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 4 (CommonAttackDamage)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[3] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // CommonAttackCoolTime (float)
                try { data.CommonAttackCoolTime = ParseFloat(cells[4]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 5 (CommonAttackCoolTime)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[4] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // AttackRange (float)
                try { data.AttackRange = ParseFloat(cells[5]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 6 (AttackRange)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[5] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Defense (float)
                try { data.Defense = ParseFloat(cells[6]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 7 (Defense)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[6] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // MoveSpeed (float)
                try { data.MoveSpeed = ParseFloat(cells[7]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 8 (MoveSpeed)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[7] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Level (int)
                try { data.Level = ParseInt(cells[8]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 9 (Level)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[8] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Exp (int)
                try { data.Exp = ParseInt(cells[9]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 10 (Exp)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[9] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // Gold (int)
                try { data.Gold = ParseInt(cells[10]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 11 (Gold)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[10] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // SearchRange (float)
                try { data.SearchRange = ParseFloat(cells[11]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 12 (SearchRange)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[11] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }
                // RespawnTime (float)
                try { data.RespawnTime = ParseFloat(cells[12]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 13 (RespawnTime)\n" +
                        "  타입: float\n" +
                        "  값: \"" + cells[12] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _monsterDict[data.Id] = data;
                    _monsterList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Monster] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Monster 로드 완료: " + _monsterList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Monster 다운로드 실패: " + ex.Message);
        }
    }

    async Task Fetch_Player()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Player");
        try
        {
            string raw = await Http.GetStringAsync(url);
            _playerDict.Clear();
            _playerList.Clear();

            List<string[]> rows = GvizParser.Parse(raw, colCount: 1);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                int sheetRow = i + 1;
                PlayerMetaData data = new PlayerMetaData();
                bool rowOk = true;

                // Id (int)
                try { data.Id = ParseInt(cells[0]); }
                catch (Exception e)
                {
                    Console.Error.WriteLine("[SpecDataManager] [Player] 파싱 오류\n" +
                        "  위치: 시트 행 " + sheetRow + ", 열 1 (Id)\n" +
                        "  타입: int\n" +
                        "  값: \"" + cells[0] + "\"\n" +
                        "  원인: " + e.Message);
                    rowOk = false;
                }

                if (rowOk)
                {
                    _playerDict[data.Id] = data;
                    _playerList.Add(data);
                }
                else
                {
                    Console.Error.WriteLine("[SpecDataManager] [Player] 행 " + sheetRow + " 파싱 오류로 스킵됨.");
                }
            }
            Console.WriteLine("[SpecDataManager] Player 로드 완료: " + _playerList.Count + "개");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("[SpecDataManager] Player 다운로드 실패: " + ex.Message);
        }
    }

    public CurrencyMetaData GetCurrency(int id)
    {
        _currencyDict.TryGetValue(id, out CurrencyMetaData result);
        return result;
    }

    public CurrencyMetaData GetCurrency(CurrencyType key)
    {
        return GetCurrency((int)key);
    }

    public List<CurrencyMetaData> GetAllCurrency()
    {
        return _currencyList;
    }

    public ItemMetaData GetItem(int id)
    {
        _itemDict.TryGetValue(id, out ItemMetaData result);
        return result;
    }

    public List<ItemMetaData> GetAllItem()
    {
        return _itemList;
    }

    public EquipmentMetaData GetEquipment(int id)
    {
        _equipmentDict.TryGetValue(id, out EquipmentMetaData result);
        return result;
    }

    public List<EquipmentMetaData> GetAllEquipment()
    {
        return _equipmentList;
    }

    public ConsumableMetaData GetConsumable(int id)
    {
        _consumableDict.TryGetValue(id, out ConsumableMetaData result);
        return result;
    }

    public List<ConsumableMetaData> GetAllConsumable()
    {
        return _consumableList;
    }

    public MiscMetaData GetMisc(int id)
    {
        _miscDict.TryGetValue(id, out MiscMetaData result);
        return result;
    }

    public List<MiscMetaData> GetAllMisc()
    {
        return _miscList;
    }

    public QuestDefinitionMetaData GetQuestDefinition(int id)
    {
        _questDefinitionDict.TryGetValue(id, out QuestDefinitionMetaData result);
        return result;
    }

    public QuestDefinitionMetaData GetQuestDefinition(QuestType key)
    {
        return GetQuestDefinition((int)key);
    }

    public List<QuestDefinitionMetaData> GetAllQuestDefinition()
    {
        return _questDefinitionList;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(int id)
    {
        _questObjectiveDefinitionDict.TryGetValue(id, out QuestObjectiveDefinitionMetaData result);
        return result;
    }

    public QuestObjectiveDefinitionMetaData GetQuestObjectiveDefinition(QuestObjectiveType key)
    {
        return GetQuestObjectiveDefinition((int)key);
    }

    public List<QuestObjectiveDefinitionMetaData> GetAllQuestObjectiveDefinition()
    {
        return _questObjectiveDefinitionList;
    }

    public MonsterMetaData GetMonster(int id)
    {
        _monsterDict.TryGetValue(id, out MonsterMetaData result);
        return result;
    }

    public MonsterMetaData GetMonster(MonsterType key)
    {
        return GetMonster((int)key);
    }

    public List<MonsterMetaData> GetAllMonster()
    {
        return _monsterList;
    }

    public PlayerMetaData GetPlayer(int id)
    {
        _playerDict.TryGetValue(id, out PlayerMetaData result);
        return result;
    }

    public List<PlayerMetaData> GetAllPlayer()
    {
        return _playerList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default;
        return (T)Enum.Parse(typeof(T), s, true);
    }
    static List<T> ParseList<T>(string s, Func<string, T> parseItem)
    {
        var result = new List<T>();
        if (string.IsNullOrEmpty(s)) return result;
        s = s.Trim();
        if (s.Length > 0 && s[0] == '{') s = s.Substring(1);
        if (s.Length > 0 && s[s.Length - 1] == '}') s = s.Substring(0, s.Length - 1);
        if (string.IsNullOrEmpty(s)) return result;
        foreach (var item in s.Split(','))
        {
            string t = item.Trim();
            if (!string.IsNullOrEmpty(t)) result.Add(parseItem(t));
        }
        return result;
    }
}
}
