// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System.Collections.Generic;

public static class GoogleSheetConfig
{
    public const string SpreadsheetId = "1I3ClbfFILySaBlP5TddE2I7xaxMrN7s-5sxXAocGoPE";

    public static readonly List<string> SheetNames =
        new List<string>
    {
        "Currency",
        "Item",
        "Equipment",
        "Consumable",
        "Misc",
        "QuestDefinition",
        "QuestObjectiveDefinition",
        "Projectile",
        "Exp",
        "Monster",
        "DropItem",
        "Player",
        "Config",
    };

    public static string BuildJsonUrl(string sheetName)
    {
        return string.Format(
            "https://docs.google.com/spreadsheets/d/{0}/gviz/tq?tqx=out:json&sheet={1}",
            SpreadsheetId, System.Uri.EscapeDataString(sheetName));
    }
}
