// ============================================================
// Auto-generated by SpecDataGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 GenSpecData.bat 재실행.
// ============================================================
using System;
using Google.Protobuf.Protocol;

// 모든 MetaData 클래스는 이 파일에서 통합 관리합니다.

// ── Currency
[Serializable]
public class CurrencyMetaData
{
    public int Id;
    public CurrencyType CurrencyType;
}

// ── QuestDefinition
[Serializable]
public class QuestDefinitionMetaData
{
    public int Id;
    public int QuestId;
    public QuestType QuestType;
    public string Title;
    public int ReqLevel;
    public int PrereqQuestId;
    public int RewardId;
    public int RewardAmount;
    public string Description;
}

// ── QuestObjectiveDefinition
[Serializable]
public class QuestObjectiveDefinitionMetaData
{
    public int Id;
    public int MainQuestId;
    public int SubQuestId;
    public QuestObjectiveType QuestObjectiveType;
    public int TargetId;
    public int RequiredCount;
    public int RewardId;
    public int RewardAmount;
    public string Description;
}

// ── Monster
[Serializable]
public class MonsterMetaData
{
    public int Id;
    public MonsterType MonsterType;
    public int MaxHp;
    public float CommonAttackDamage;
    public float CommonAttackCoolTime;
    public float AttackRange;
    public float Defense;
    public float MoveSpeed;
    public int Level;
    public int Exp;
    public int Gold;
    public float SearchRange;
    public float RespawnTime;
}

// ── Player
[Serializable]
public class PlayerMetaData
{
    public int Id;
}
