// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================

public enum ConfigType
{
    None = 0,
    RequiredIdleTime,
}

