// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.DB;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260402151541_AddStatSystem")]
    partial class AddStatSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.DB.AccountDb", b =>
                {
                    b.Property<int>("AccountDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountDbId"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountDbId");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Server.DB.PlayerDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerDbId"));

                    b.Property<int>("AccountDbId")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<bool>("IsStatInitialized")
                        .HasColumnType("bit");

                    b.Property<int>("Jewel")
                        .HasColumnType("int");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<float>("LastPosX")
                        .HasColumnType("real");

                    b.Property<float>("LastPosY")
                        .HasColumnType("real");

                    b.Property<float>("LastPosZ")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("StatAttackHalfAngleDeg")
                        .HasColumnType("real");

                    b.Property<float>("StatAttackHeight")
                        .HasColumnType("real");

                    b.Property<float>("StatAttackRange")
                        .HasColumnType("real");

                    b.Property<float>("StatCommonAttackCoolTime")
                        .HasColumnType("real");

                    b.Property<float>("StatCriticalDamage")
                        .HasColumnType("real");

                    b.Property<float>("StatCriticalRate")
                        .HasColumnType("real");

                    b.Property<int>("StatDEX")
                        .HasColumnType("int");

                    b.Property<int>("StatDefense")
                        .HasColumnType("int");

                    b.Property<int>("StatINT")
                        .HasColumnType("int");

                    b.Property<int>("StatLUK")
                        .HasColumnType("int");

                    b.Property<int>("StatMagicDamage")
                        .HasColumnType("int");

                    b.Property<int>("StatMaxHp")
                        .HasColumnType("int");

                    b.Property<float>("StatMoveSpeed")
                        .HasColumnType("real");

                    b.Property<int>("StatPhysicalDamage")
                        .HasColumnType("int");

                    b.Property<int>("StatSTR")
                        .HasColumnType("int");

                    b.HasKey("PlayerDbId");

                    b.HasIndex("AccountDbId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Server.DB.PlayerItemDb", b =>
                {
                    b.Property<int>("PlayerItemDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerItemDbId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("EnchantLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("RestEnchantCount")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("PlayerItemDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("PlayerItem");
                });

            modelBuilder.Entity("Server.DB.QuestDb", b =>
                {
                    b.Property<int>("QuestDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestDbId"));

                    b.Property<DateTime>("ClearedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MainQuestId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubQuestId")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("QuestDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("Server.DB.PlayerDb", b =>
                {
                    b.HasOne("Server.DB.AccountDb", "Account")
                        .WithMany("Players")
                        .HasForeignKey("AccountDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Server.DB.PlayerItemDb", b =>
                {
                    b.HasOne("Server.DB.PlayerDb", null)
                        .WithMany("Items")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.DB.QuestDb", b =>
                {
                    b.HasOne("Server.DB.PlayerDb", null)
                        .WithMany("Quests")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.DB.AccountDb", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Server.DB.PlayerDb", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Quests");
                });
#pragma warning restore 612, 618
        }
    }
}
